name: Update index

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      clear_cache:
        description: 'Clear cache'
        required: true
        type: boolean 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up state
      uses: actions/cache@v3
      with:
        path: state
        key: state
        
    - name: Optionally clear cache
      if: ${{ inputs.clear_cache }}
      run: rm state/*
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build index
      run: ./build.sh
    
    - name: Upload index
      uses: actions/upload-artifact@v3.1.2
      with:
        name: index.zst
        path: index.zst
