name: Update index
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      clear_cache:
        description: 'Clear cache'
        required: true
        type: boolean 
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up state
      uses: actions/cache@v3
      with:
        path: state
        key: state
    - name: Optionally clear cache
      if: ${{ inputs.clear_cache }}
      run: rm state/lasthash
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build index
      run: ./build.sh
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "out/index.zst"
    - name: Setup Pages
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/configure-pages@v3
    - name: Upload artifact
      if: steps.check_files.outputs.files_exists == 'true'
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'out'
    - name: Deploy to GitHub Pages
      if: steps.check_files.outputs.files_exists == 'true'
      id: deployment
      uses: actions/deploy-pages@v1
